server:
    port: 8000
spring:
  application:
      name: blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    username: root
    password: 123456
    url: jdbc:mysql//localhost:3306/blog?useUnicode=true&characterEncoding=utf8
    dbcp2:
      　　min-idle: 5         #数据库连接池的最小维持连接数
      　　initial-size: 5     #初始化提供的连接数
      　　max-total: 5          #最大的连接数
      　　max-wait-millis: 200        #等待连接获取的最大超时时间
  redis:
    host: localhost
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.tyzz.blog.entity
  configuration:
    map-underscore-to-camel-case: true